language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - libtiff-devel
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++17"
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - libtiff-devel
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++14"
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
            - libtiff-devel
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++11"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++17"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++14"
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++11"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++1z"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++14"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++11"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ls
  - $COMPILER --version
  - $COMPILER -ltiff src/main.cpp src/args.cpp src/tiffer.cpp -o tiffer
  - ./tiffer
  - ./tiffer -help
  - ./tiffer -version
  - ./tiffer test/*.tif -output all.tif
  - ./tiffer test/*.tif -output noblank.tif -remove-blank
  - ./tiffer test/*.tif -clobber -output noblank.tif -remove-blank -remove-pages 2,4,5-9
