language: cpp 
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++17"
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - libstdc++-7-dev
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0 && COMPILER=clang++-5.0 && CXXSTD=c++14"
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++ && COMPILER=clang++ && CXXSTD=c++11"
#    - os: linux
#      dist: trusty
#      compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++17"
#    - os: linux
#      dist: trusty
#      compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-7
#      env:
#        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && COMPILER=g++-7 && CXXSTD=c++14"
#    - os: linux
#      dist: trusty
#      compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++
#      env:
#        - MATRIX_EVAL="CC=gcc && CXX=g++ && COMPILER=g++ && CXXSTD=c++11"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++1z"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++14"
    - os: osx
      osx_image: xcode9.3
      env:
        - MATRIX_EVAL="brew update && brew install gcc && COMPILER=clang++ && CXXSTD=c++11"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - $COMPILER --version
  - $COMPILER -std=c++11 -ltiff src/main.cpp src/args.cpp src/tiffer.cpp -o tiffer
  - ./tiffer
  - ./tiffer -help
  - ./tiffer -version
  - ./tiffer test/*.tif -output all.tif
  - test `wc -c all.tif` == '2225288 all.tif'
  - ./tiffer test/*.tif -output noblank.tif -remove-blank
  - test `wc -c noblank.tif` == '2222368 noblank.tif'
  - ./tiffer test/*.tif -clobber -output noblank.tif -remove-blank -remove-pages 2,4,5-9
  - test `wc -c noblank.tif` == '1580870 noblank.tif'

#deploy:
#  provider: releases
#  api_key: "GITHUB OAUTH TOKEN"
#  file: tiffer
#  skip_cleanup: true
#  on:
#    tags: true
